### ISSUE TITLE
Laggy input, especially on mobile

### ISSUE THREAD

**Issue by djibux** [owncloud/tasks#115]
Text input is quite slow on almost all text inputs.  It is quite obvious on slow computers or mobile devices.

**Comment by djibux** [comment]
I understand this might be considered an enhancement, but as is, the app is hard to use on a mobile. Text input lags by a few seconds.

**Comment by raimund-schluessler** [comment]
I must admit I don't use the app on my mobile as I use the native clients there.
Which text input do you mean especially? Input of task names, notes, comments or other things? All text is parsed by AngularJS which is integral part of the app. So, if it is laggy, this is due to AngularJS, which is why I don't think I can do to much about it.

**Comment by djibux** [comment]
Hello. There unfortunately aren't native clients for tasks on Firefox OS so far. :'(

All inputs are quite slow (adding a task, changing the name of a task, adding a description, …).  It's especially annoying when adding tasks.  (By the way I also think you shouldn't blur the field right after a task has been entered to allow entering multile tasks quickly).

I'm not sure how I can help you on that but I am available should you need help.
Maybe the first thing would be to wait and see if others complain about the same issue.

**Comment by GCastor** [comment]
BTW the android tasks clients aren't 100% function compatible with owncloud tasks. So the mobile tasks version is really fine , but text inputs are really too slow for working on firefox :/

Atom quad 1.33-1.8Ghz & ARM quad 2.1Ghz  --> unusable.

Come on, its just a text input like displayed in html 2. 20 years ago xD
