### ISSUE TITLE
-505

### ISSUE THREAD

**Issue by Hansxa** [owncloud/tasks#118]
trying to install and connect to my owncloud gives me Error "-505"

**Comment by nodiscc** [comment]
@Hansxa Is this related to the _Tasks_ app in Owncloud? Because this is what this bug tracker is about. If it's not about the tasks app, please close this issue.

If you're looking for support on installing Owncloud on your own server, I suggest going to http://forum.owncloud.org/ and asking there. You will need to provide more details such as: what is your OS/webserver/general configuration, how did you install owncloud, where/when do you get this error. Try to provide as much relevant details as possible when reporting a bug. Good luck!

**Comment by Hansxa** [comment]
this error appears when trying to install the tasks app for owncloud from play store on android 5 nexus 4.
owncloud runs properly without ssl, calDAV app is installed on mobile device and properly connected to owncloud.

-------- Originalnachricht --------
Betreff: Re: [tasks] -505 (#118)
Von: nodiscc <notifications@github.com>
An: owncloud/tasks <tasks@noreply.github.com>
Cc: Hansxa <brennpunkt-ostkreuz@web.de>

**Comment by raimund-schluessler** [comment]
This app here has nothing to do with "the tasks app for owncloud from play store on android 5 nexus 4". I didn't even know such an app exists.

**Comment by Hansxa** [comment]
https://owncloud.tu-berlin.de/public.php?service=files&t=8c978def35c259cb6c1a8164b4990568

Sent by berlindelta

-------- Originalnachricht --------
Betreff: Re: [tasks] -505 (#118)
Von: nodiscc <notifications@github.com>
An: owncloud/tasks <tasks@noreply.github.com>
Cc: Hansxa <brennpunkt-ostkreuz@web.de>

**Comment by raimund-schluessler** [comment]
Sorry, but as I said, this is not the correct repository for your error. This app here is an app directly for the web front end of owncloud and does not provide an android app (have a look at the screenshots under https://apps.owncloud.com/content/show.php/Tasks?content=164356). Furthermore, the errorcode of your android app is rather meaningless and I doubt that it is related to owncloud at all as it appears when trying to install.

**Comment by nodiscc** [comment]
@Hansxa this is the repository you're looking for https://github.com/dmfs/tasks

**Comment by raimund-schluessler** [comment]
Thanks for the clarification @nodiscc.
