### ISSUE TITLE
Animations take too long

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#188]
The animation to show the task details takes to long and may annoy users.
When switching between lists the tasks seem to be reordered. This could irritate the users.

We should probably remove the animation between lists and shorten or remove the animation for the task details.
Maybe it is even a good idea to always show the task details.

**Comment by Henni** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
I would say as first pass:
* Remove the animations between lists. They are confusing since they convey the feeling that the tasks morph – but they are not necessarily the same.
* Make the animation of the right sidebar moving in exactly as fast as the apps menu and user menu opening.

The other stuff can stay the same for now, I think with those 2 enhancements it will look a lot better already. :)
