### ISSUE TITLE
New description is lost after reload

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#194]
After adding a new description to a task and immediately reloading the page the description is lost.

It looks to me as if the description is only saved if another task is selected before reloading the page.
I would suggest to listen for the blur event of the textarea and save the content if the user clicks outside of the textarea.

**Comment by raimund-schluessler** [comment]
The title, note and completed value are saved after 1 s, 5 s and 3 s, respectively. See https://github.com/owncloud/tasks/blob/master/js/app/controllers/detailscontroller.coffee#L230-L254

These timers are indeed canceled by a page reload and I don't know if the blur event triggers when reloading the page.

**Comment by Henni** [comment]
Do you think we should add a blur listener or are these timeouts good enough?

**Comment by Henni** [comment]
@raimund-schluessler what do we do about this?

**Comment by raimund-schluessler** [comment]
@Henni Don't reload the page to soon  :see_no_evil:

No, seriously, we should fix this indeed, but I think it is an edge case, which may not be easy to fix (since we first need to have an idea on how to fix it) and is rather an annoyance than a critical bug.

I would say we can release v0.7 without a fix for this and think about resolving it unhurriedly.

**Comment by raimund-schluessler** [comment]
The description is now saved after one second. I am not aware of a possibility to do stuff before a page reloads. If there is, let me know.
