### ISSUE TITLE
Linkify urls in issues and comments

### ISSUE THREAD

**Issue by icewind1991** [owncloud/tasks#252]
When a url is part of the issue title or part of a comment it should be transformed in a clickable link

**Comment by raimund-schluessler** [comment]
Was already asked for in https://github.com/owncloud/tasks/issues/154. However, I will close the older issue in favor of this one, as here comments are mentioned too.

Does someone know if there is already a function in core which could handle this? Otherwise we will just use the custom javascript function already used for parsing links in notes.

**Comment by icewind1991** [comment]
Afaik we have nothing in core for it

**Comment by icewind1991** [comment]
When linkifying it might also be nice to fetch some info from the link (title, favicon, some domain specfic data maybe) and show it in the task/comment somehow.

My main usecase for that is linking github issues/prs to tasks and it would be nice if I could get the issue title and status right in the task

**Comment by raimund-schluessler** [comment]
Sound interesting. We need to figure out how to load (only) this data.

**Comment by Gomez** [comment]
Miss this feature too. 
We tried to add it to the Mail App (with regex), but failed partly. Some infos are here:

https://github.com/owncloud/mail/issues/641
https://github.com/owncloud/mail/issues/930

Maybe we can help each other, a "perfect" solution is not yet found.

**Comment by raimund-schluessler** [comment]
We also use Regex to parse links in notes, see https://github.com/owncloud/tasks/blob/master/js/app/directives/clickableurl.coffee#L32-L48.

However, I fear these regex are not perfect either, a unified solution would be very welcome.
