### ISSUE TITLE
Also show URL field of tasks

### ISSUE THREAD

**Issue by llucax** [owncloud/tasks#278]
https://github.com/dmfs/opentasks/ is a very nice Android app for manipulating tasks too. I noticed some stuff that can be set in that app is not reflected in this owncloud app and viceversa. For example URLs set in the opentasks app are not visible in the this owncloud app, and comments added via this app are not visible in the opentasks app.

Although the basic stuff works, it would be nice if both apps could have a better interaction.

**Comment by raimund-schluessler** [comment]
This app here uses the standard fields for storing comments as defined in https://tools.ietf.org/html/rfc5545#page-118, so for showing the comments in Opentasks you should open an issue there.

I guess the URL in Opentasks is stored in the URL field, which is indeed not evaluated by the Tasks app.

So this issue is basically not about compatibility, but rather also showing the URL field of a Task.
