### ISSUE TITLE
important / all / current / finished shows an empty page

### ISSUE THREAD

**Issue by tchncs** [owncloud/tasks#285]
Hi, one of my two ownClouds only shows empty pages on this four top-categorys:

![2015-12-14-165719_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/11785963/69e1d42c-a284-11e5-90a7-570fab99830d.png)

I checked the logs for errors -> nothing
I re-cloned and double checked permissions of the tasks app -> no change
I also checked checked the permissions for calendar -> again, no change.

Maybe someone here have some idea whats broken?
 ownCloud 8.2.1 (stable) is installed.

**Comment by tsamm** [comment]
Same here.  The funny thing is, Owncloud itself seems to work as well as the plugin. It's the CSS that seems to be buggy at least with some browsers (FF on Linux in my case).

**Comment by raimund-schluessler** [comment]
@tsamm So this does mean it works normally on other browsers?

@tchncs Could you please check if this is the case for you too? And please specify exactly on which setup it doesn't work.

**Comment by tsamm** [comment]
@raimund-schluessler Negative. Opera doesn't work either :( 
Nevertheless none of the logs on the server are indicating any kind of error. The HTML source is complete and looks perfectly OK. CSS/DOM inspector shows plenty of elements but none are displayed in the rendered page.

**Comment by tchncs** [comment]
I checked the following now:

Opera 34.0
Chromium 47.0.2526.111
Firefox 43.0.4
..on ArchLinux.

...I really dont think, thats on the browserside because another owncloud with nearly the same (dont what should be different) setup just works fine.

regards

**Comment by raimund-schluessler** [comment]
Can you please check, whether the tasks are loaded? You should see a call to
```<owncloud>/index.php/apps/tasks/tasks/init/all``` which should contain your tasks.

This error will be hard to tackle if we don't know under which circumstances it appears.

**Comment by raimund-schluessler** [comment]
Nevermind, I just saw that they are loaded as their count is shown at the left navigation bar. This leaves me even more puzzled.

**Comment by BeuthHS-Webteam** [comment]
Maybe it helps: In my case, the smart collections "Week" and "Completed" show the count and the tasks. "Important", "Today", "All" and "Current" just have their count shown, however, no tasks.

(I'm using Ubuntu trusty, Firefox v44. Same behaviour with Midori and Chrome v48. I also tested Windows 7 with IE11 and Firefox v44; Andoid 5.1.1 with Chrome; - all combinations: same same.)

regards
.Thomas

**Comment by m4tu5** [comment]
Same on Owncloud 8.1.3 (git) and using Tasks master branch

**Comment by m4tu5** [comment]
@tsamm,

> CSS/DOM inspector shows plenty of elements but none are displayed in the rendered page. 
any idea why?

**Comment by raimund-schluessler** [comment]
Could you please give more information about your setup? E.g. the database it is running on. Best would be using the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Maybe we can find a pattern.

**Comment by tsamm** [comment]
@m4tu5 Absolutely no clue - and I don't see any chance of finding out.

**Comment by tsamm** [comment]
@raimund-schluessler config details attached
[config.txt](https://github.com/owncloud/tasks/files/111871/config.txt)

**Comment by m4tu5** [comment]
GET/all returns a JSON with all tasks in it. They are not listed in any of the collections (e.g. all, today, week, important, etc.), but are properly listed in the individual lists (a.k.a. calendars/task lists)

**Comment by m4tu5** [comment]
# ISSUE REPORT # 

### Steps to reproduce
1. Create a new task in any calendar
2. Access the Tasks app

### Expected behaviour
Tasks should be listed in collections (all, today, week, important) as well as in individual taks lists

### Actual behaviour
Tasks are not shown in the collections (central content only shows new task div)
The numeric indicator of how many tasks are in each collection works fine.
Tasks are properly shown when accesing a list(calendar) instead of a collection

### Server configuration
**Operating system**:
Parabola (free software Arch alternative)
4.3.3-gnu-3
x86_64

**Web server:**
nginx version: nginx/1.8.0

**Database:**
Postgres

**PHP version:**
PHP 5.6.16 (cli) (built: Dec  6 2015 20:35:16)

**ownCloud version:** (see ownCloud admin page)
8.1.3 (git)

**Updated from an older ownCloud or fresh install:**
Updated from older OwnClouds

**Signing status (ownCloud 9.0 and above):**
N/A
```
Login as admin user into your ownCloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc4c8061dd68',
  'passwordsalt' => <sanitized>,
  'trusted_domains' =>
  array (
    0 => 'oc.sanitized.com',
    1 => 'oc.sanitized.net',
  ),
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'dbtype' => 'pgsql',
  'dbname' => <sanitized>,
  'dbuser' => <sanitized>,
  'dbpassword' => <sanitized>,
  'dbhost' => '/var/run/postgresql',
  'version' => '8.1.3.0',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'theme' => '',
  'maintenance' => false,
  'secret' => <sanitized>,
  'default_language' => 'es',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
* Firefox 43.0-1
* Chromium 47.0.2526.80-2

**Operating system:**
Archlinux 4.2.5-1-ARCH x86_64

### Logs
#### Web server error log
```
feb 01 07:40:26 <host> nginx[406]: 2016/02/01 07:40:26 [error] 734#0: *12834 open() "/srv/http/oc.sanitized.com404" failed (2: No such file or directory), client: <client_ip>, server: oc.sanitized.com, request: "GET /apps/tasks/js/vendor/angularjs/angular.min.js.map HTTP/1.1", host: "oc.sanitized.com"
feb 01 07:40:27 <host> nginx[406]: 2016/02/01 07:40:27 [error] 734#0: *12834 open() "/srv/http/oc.sanitized.com404" failed (2: No such file or directory), client: <client_ip>, server: oc.sanitized.com, request: "GET /apps/tasks/js/vendor/angularjs/angular-route.min.js.map HTTP/1.1", host: "oc.sanitized.com"
feb 01 07:40:27 <host> nginx[406]: 2016/02/01 07:40:27 [error] 734#0: *12834 open() "/srv/http/oc.sanitized.com404" failed (2: No such file or directory), client: <client_ip>, server: oc.sanitized.com, request: "GET /apps/tasks/js/vendor/angularjs/angular-animate.min.js.map HTTP/1.1", host: "oc.sanitized.com"
feb 01 07:40:27 <host> nginx[406]: 2016/02/01 07:40:27 [error] 734#0: *12834 open() "/srv/http/oc.sanitized.com404" failed (2: No such file or directory), client: <client_ip>, server: oc.sanitized.com, request: "GET /apps/tasks/js/vendor/angularjs/angular-sanitize.min.js.map HTTP/1.1", host: "oc.sanitized.com"

#### ownCloud log (data/owncloud.log)
Nothing gets written in the log when loading the Tasks view

#### Browser log
```
a) The javascript console log (from Firefox)

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead       jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://oc.sanitized.com 'unsafe-eval'").    [5 repeats]   tasks
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.            jquery.min.js:5:17117
Use of getAttributeNode() is deprecated. Use getAttribute() instead.                jquery-migrate.min.js:2:1616
Use of attributes' nodeValue attribute is deprecated. Use value instead.            jquery-migrate.min.js:2:1616
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://oc.sanitized.com 'unsafe-eval'").                   tasks:1:0

b) The network log

All the GET methods are shown with green status
GET/all returns a JSON with all the Tasks that are not shown on the collections views
```

**Comment by tchncs** [comment]
Switching to DAVclient branch fixes this issue for me.
