### ISSUE TITLE
Task list not updated in DAVClient branch

### ISSUE THREAD

**Issue by guidtz** [owncloud/tasks#298]
Hello,

   I test tasks in owncloud 9 with DAVClient branch and when I create a new calendar it is not updated in tasks list.

Thanks

**Comment by raimund-schluessler** [comment]
How do you create the new calendar?

**Comment by guidtz** [comment]
Normally with '+ New Calendar' in calendar standard app.

**Comment by raimund-schluessler** [comment]
This is by design. If you want to create a new task list, you have to use the Tasks app. Tasks and Calendar are separate apps, they only share the same CalDAV backend included in core.

If you want calendars created in the Calendar app to appear in the Tasks app, you will have to ask the Calendar developers to change https://github.com/owncloud/calendar/blob/master/js/app/service/calendarservice.js#L166 to also specify ```VTodo```.

Btw.: Lists i.e. calendars created in the Tasks app won't appear in the Calendar app either.

Maybe we should discuss if this is wanted or not: @jancborchardt @georgehrke

**Comment by guidtz** [comment]
Ok I understand, but in owncloud 8 this features works when we create a calendar a task list linked to the calendar is created.
Also for sharing task we can create a share calendar and add task on this list is shared between users.

**Comment by raimund-schluessler** [comment]
As I said, it could work in OC 9 too, it just has to be specified when creating the calendar or task list.
Sharing will be implemented in the Tasks app.

**Comment by guidtz** [comment]
Issue is created.

`Sharing will be implemented in the Tasks app.` : when do you think this will be implemented ? I think is a great features for users.

**Comment by jancborchardt** [comment]
I’d say to keep it simple, tasklists/calendars should be shared always, like they were in the past. iOS does it similarly.

**Comment by georgehrke** [comment]
@jancborchardt What if I want a task list like `Groceries`. That should definitely not be a calendar

**Comment by jancborchardt** [comment]
True true. But we should do one step in some direction. Maybe it’s most sensible to show all Calendars as task lists, but not the other way around. Because normally you have more (and more specific) task lists than calendars.

**Comment by georgehrke** [comment]
Okay, so If you create a new calendar in the calendar app it should be capable of both, events and todos, and if you create a new calendar in the task app, it should only be able to store tasks.
Let's do it!

**Comment by wobblywob** [comment]
I don't know where I'm supposed to ask this. If I create a calendar in Calendars, it automatically creates a task list in Tasks. If I create an event in one of them it doesn't show up in the other. Is this expected behavior?

**Comment by guidtz** [comment]
It's works now but when I post the issues It did not work.

**Comment by wobblywob** [comment]
Yes, calendar creation works for me too, but events created in one place don't show up in the other. I wanted to know if they should sync or not.

**Comment by guidtz** [comment]
Personnaly I think task with start date must be appear in calendar but event in calendar must not appear in task. It's my point of view

**Comment by wobblywob** [comment]
So, at the moment, events created in calendar are not synced to tasks (or tasks to calendar).

**Comment by raimund-schluessler** [comment]
Events (VEVENT) and Tasks (VTODO) are totally different things. They are stored in the same Calendar, but they won't show up in the other app. That's why these apps are called "Tasks" and "Calendar".

We could discuss that tasks with a start AND end date can appear in the calendar, but that is a different issue: https://github.com/owncloud/tasks/issues/19
