### ISSUE TITLE
Very slow in OC 9

### ISSUE THREAD

**Issue by dynobo** [owncloud/tasks#302]
The speed of Tasks-App decreased a lot after my switch from OC 8 to 9. Especially switching between different lists or opening the details of a task is very slow, sometimes even freezing the Firefox and causing the "Script on Website is not responding"-Warning.

**Comment by raimund-schluessler** [comment]
This is because the DAVclient branch currently loads all tasks there are on the server, whether or not they are completed. If you have been using Tasks for a long time, there might be several hundred or thousand completed tasks which all are loaded into the app. This makes it slow, since the app has to iterate over all tasks to check if they have to be shown to the user.

I am aware of this problem and will cover it as it has been done in the older version: only load uncompleted tasks.

**Comment by raimund-schluessler** [comment]
A fist workaround can be found in the DAVclient branch now: https://github.com/owncloud/tasks/pull/291. Only not completed tasks are loaded at the moment. I still have to implement an option to also load completed tasks on demand though.

**Comment by raimund-schluessler** [comment]
Fixed now in Davclient branch.
