### ISSUE TITLE
Integrity Check Error

### ISSUE THREAD

**Issue by bahamut714** [owncloud/tasks#337]
The issue should not have been closed unresolved. Here is the fix, comment out the lines checking the app signature from Installer.php and Checker.php in lib/private.

https://github.com/search?l=php&q=org%3Aowncloud+Signature+could+not+get+checked&type=Code

 Why is there a signature check anyway? If somebody has access to installing applications into your admin panel, you are already owned. You should only obtain apps from verified sources, so there is no issue of signature checking unless you are attempting to create some type of Apple/iOS closed off app ecosystem.

It is very bizarre to expect all app devs to update their signatures on every update of owncloud and for users to just be completely out of luck until that happens for every app they were trying to use.

**Comment by raimund-schluessler** [comment]
Sorry to say that, but nearly everything you wrote in your weird rant against app-signing is simply wrong.

> The issue should not have been closed unresolved.

First of all, the issue (I guess you are referring to https://github.com/owncloud/tasks/issues/328) is not closed. It is still open, it is confirmed, it will be resolved soon and no further information is necessary. However, it is locked for a reason: To prevent people like you wasting my time. Of course you are welcome to open new issues if necessary and express your opinion about what to improve on the app. But please keep in mind: While I answer your post, inform you about something you could have informed yourself by using google and correct your wrong coneptions, I could have worked on the app (or at least do something more pleasant than answering you).

> Here is the fix, comment out the lines checking the app signature from Installer.php and Checker.php in lib/private.

This is not fix, but a stupid hack. Of course no one will prevent you from doing so, Owncloud and the Tasks app are free software, so do what you want. **But to everybody else:** Please do not disable the integrity check. It does add an extra layer of security and it does not restrict your freedom to install whatever you want:

> Why is there a signature check anyway? If somebody has access to installing applications into your admin panel, you are already owned. You should only obtain apps from verified sources, so there is no issue of signature checking unless you are attempting to create some type of Apple/iOS closed off app ecosystem.

An easy google search lead to the following: https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html#do-we-lock-down-owncloud
App signing does not restrict you, it will not prevent the app from running and it is optional. However, it guarantees your "verified sources". By signing the code, you can be sure, that the developer of the app (me) wrote the code you are installing on your server. It ensures that it was not changed by someone else. Now you could argue if it is reasonable to trust me. But I guess if you install the app I wrote, you somewhat have to trust me, that the code isn't doing any evil. Otherwise, go write your own Tasks app (and owncloud). So this is far form a "closed off app ecosystem".

> It is very bizarre to expect all app devs to update their signatures on every update of owncloud and for users to just be completely out of luck until that happens for every app they were trying to use.

If you would have read #328 before you expressed yourself, you would have seen that it is not necessary to get a new certificate for each release. My old certificate was revoked because my laptop got stolen and so someone else could have signed code in my name. Also I hadn't have time to get a new certificate on time, which was only my fault. Otherwise there wouldn't be this issue here.

Also you are not "out of luck", because the app is still working. The only problem you have is a little warning in your free and gratis app which does not do any harm. If this really bothers you this much, I am deeply sorry for you.

Also: I am going to close this issue here, there is nothing more to say about app-signing and the Tasks app.

**Comment by bahamut714** [comment]
I am not surprised your company is going to fail. What a complete loser.

**Comment by raimund-schluessler** [comment]
FYI: I am a private developer. I am not associated with the commercial part of owncloud, but I consider myself part of the free owncloud community. I develop this app in my freetime and I give it away for free. I am always interested in usefull proposals to improve it. But you simply gave wrong information and now start to insult me for correcting you. People like you make me think about writing free software, because I would very much like to forbid you to use it. But it is and will be free software so also ******* like you are allowed to use it.

So to make things clear: I am not interested in you using my app, so go use something else. I couldn't care less.

**Comment by bahamut714** [comment]
That's fine, I have switched to seafile instead. Good luck with your little project.

**Comment by raimund-schluessler** [comment]
Great news, go on with insultig them, they will like it for sure.

**Comment by bahamut714** [comment]
Won't need to, it has already been working fine. The amount of time I have spent trying to get owncloud to work while they have a tantrum fit over ownership with nextcloud has been too much for me,.

**Comment by raimund-schluessler** [comment]
> Won't need to, it has already been working fine. The amount of time I have spent trying to get owncloud to work while they have a tantrum fit over ownership with nextcloud has been too much for me,.

I didn't take part in this discussion and I don't like this fork either, but it is what it is and we have to deal with it. If it's to much for I can understand that, but it has nothing to do with the Tasks app.

> And this app comes bundled with owncloud, if you are able to free yourself of responsiblity from it that is a problem for owncloud not for me.

I don't know where you get your information from, but you should really check your sources. The app is not bundled with the official owncloud release. It is distributed via the appstore, where everybody can release apps. The code hosting is just domiciled in the owncloud repository, because it makes the development easier.

Also I don't have any obligations to develop this app further. It is a community project and everybody could participate (you too!). But instead of helping, you blame me for not working for you in my freetime. Thanks for that. Furthermore, there will be a fixed release once I receive the certificate necessary to sign the app. It is just a little inconvenience, if you can't deal with it, don't use it.

**Comment by raimund-schluessler** [comment]
@bahamut714 Looks like owncloud is not the only cloud solution company with problems: https://blogs.seafile.com/2016/07/22/statement-about-stopping-cooperation-with-seafile-gmbh/

**Comment by bahamut714** [comment]
If you are going to delete messages from users maliciously that says all there needs to be said about owncloud. Furthermore, you seem to spend too much time thinking about inserting malicious code into owncloud apps that you probably have already done it.

I am happy to find out that seafile has closed off a vulnerability quickly with no damage done to users who took correct security precautions. I highly doubt owncloud and nextcloud in their current state would be capable of doing the same thing.

Go ahead and delete this message as well because you and owncloud come out looking so badly.

**Comment by raimund-schluessler** [comment]
You are one of the worst and manipulative persons I ever had to deal with. I deleted nothing, you did and I added your message to my post to record what you wrote. I will stop responding to posts from you now.

**Comment by raimund-schluessler** [comment]
You are doing it again. Original post from this guy:

> If you are going to delete messages from users maliciously that says all there needs to be said about owncloud. Furthermore, you seem to spend too much time thinking about inserting malicious code into owncloud apps that you probably have already done it.

>I am happy to find out that seafile has closed off a vulnerability quickly with no damage done to users who took correct security precautions. I highly doubt owncloud and nextcloud in their current state would be capable of doing the same thing.

> Go ahead and delete this message as well because you and owncloud come out looking so badly.

**Comment by bahamut714** [comment]
Wow, somebody edited a message on the internet. Owncloud devs hard at work.

**Comment by raimund-schluessler** [comment]
You are a funny guy. Come to think of it, please go on entertaining me :smiley:

**Comment by RealRancor** [comment]
@raimund-schluessler Don't waste you time on trolls like this. It doesn't worth the time...
