### ISSUE TITLE
Calendar "Contact birthdays" is visible and standard

### ISSUE THREAD

**Issue by Juliku** [owncloud/tasks#338]
I am on Owncloud v 9.1.0, calendar 1.3.1 and tasks 0.9.2.
The builtin calendar "Contact birthdays", which is readonly in the calendar app, shows in the tasks app. Furthermore it is the standard calendar for tasks. Both of which shouldnt happen. Is there something misconfigured on my side or is this a bug?

**Comment by raimund-schluessler** [comment]
I would not consider this a bug, but there is certainly room for improvement. The Tasks app gets the calendars from the DAV app in owncloud core via a CalDAV query. This also includes the birthday calendar which is why it is shown.
Best would be if there was a possibility to select which calendars are shown in the left sidebar (similar to the selection of smart collections). See https://github.com/owncloud/tasks/issues/138 as reference for this feature.

Also setting a default task list is necessary in order to deselect the birthday calendar. See https://github.com/owncloud/tasks/issues/149 as reference.

I close this issue here as it is actually two issues, which are tracked in the references given.

**Comment by DeepDiver1975** [comment]
> The Tasks app gets the calendars from the DAV app in owncloud core via a CalDAV query.

@raimund-schluessler are you querying for a special component type?

One solution would be to change the component field in the calendar table for the birthday calendar to VEVENT only and not VEVENT,VTODO

**Comment by raimund-schluessler** [comment]
> @raimund-schluessler are you querying for a special component type?

@DeepDiver1975 Yes, here https://github.com/owncloud/tasks/blob/master/js/public/app.js#L2287-L2298 it should filter out calendars not supporting VTODO.

This actually is a good idea, how to not show the birthday_calendar since it will never contain VTODOs.

**Comment by raimund-schluessler** [comment]
I will test https://github.com/owncloud/core/pull/25636 the next days.

**Comment by DeepDiver1975** [comment]
> I will test owncloud/core#25636 the next days.

great - thx
