### ISSUE TITLE
Recommended Mac and Linux clients?

### ISSUE THREAD

**Issue by marcbria** [owncloud/tasks#373]
Just wondering if there is any recommended (or compatible) desktop task manager application.

I found qOwnNote integrates tasks, but I'm looking for something more simple... just the same we saw on web, but without web lags.

Thanks in advance,
m.

**Comment by marcbria** [comment]
README talks about Thunderbird (without plugin?), Evolution, KDE Kontact. I will test.
Any comment about Mac?

**Comment by raimund-schluessler** [comment]
This question is a bit misplaced, because you don't need a desktop client for the Tasks app, you need a desktop client for the ownCloud CalDAV server. In fact, this app here is nothing else but a client for this CalDAV server and any desktop client will communicate with the ownCloud server independently from this app. I must admit, the Readme is a bit misleading and should be reworked.

So yes, any CalDAV client should work fine. For Thunderbird you need the Lightning addon. I can't give further information regarding Mac or Linux clients, because I don't use them.

Also, have a look at this list: https://github.com/owncloud/core/wiki/Apps

**Comment by Gerii** [comment]
Thunderbird should have the Lightning plugin now out of the box. However this varies by distro, e.g. on Ubuntu you need to install the xul-ext-lightning package. I haven't used Thunderbird's task integration that much, but a problem I've found is that you have to add every task list on its own. Should work on Mac too, but I heard Mac has its own integration of CalDAV?
I personally use Kontact which is quite nice. If you just want to use it for tasks you can just download KOrganizer which is a standalone version of Kontacts calendar and task list. However, make sure to use the latest version, as there have been some bugs with synchronization in the past.
