### ISSUE TITLE
feature: Add support for task priority

### ISSUE THREAD

**Issue by zakoon** [owncloud/tasks#77]
My corresponding task-tools for OC-stored Tasks (Thunderbird, Tasks-Android-App) both support priorities for tasks (high, medium, low, not set). Is it be possible to add this to the Task-App, too?

Thx!

**Comment by jancborchardt** [comment]
Just as a sidenote because @Henni also mentioned that the other day: I think the star/unstar is a very good method of prioritization which suffices for most people. Introducing more priorities would be little gain for few, and I would recommend it as advanced feature if anything. Youtube moved from 1-to-5-star ratings to simple thumbs up/down cause most people gave either 1 or 5 stars. ;)

I’d say instead of manual setting of importance, the ability to sort tasks is a much better way to set their importance in a more free-form fashion: https://github.com/owncloud/tasks/issues/86

**Comment by raimund-schluessler** [comment]
I currently implement to set priorities in more detail. However, I intend to keep the star/unstar method, so clicking on the star just sets the priority to highest. This way users who don't want to use the detailed priorities are not disturbed. If you want to adjust it in more detail, you can go to the detail view of the task.

**Comment by jancborchardt** [comment]
@raimund-schluessler ok. Would be cool to also work this in with the sorting in some way. But maybe it’s a different thing.

**Comment by raimund-schluessler** [comment]
It's kinda related. Tasks are sorted by priority, so adjusting this leads to a reordering of the tasks. However, I think manual sorting should be implemented to, which then overrides all other sorting options (although I still have to think of a good way to implement manual sorting).

**Comment by raimund-schluessler** [comment]
Implemented with #199
