### ISSUE TITLE
Add a start/stop button to make the taskplanner a realtime-time-tracking software

### ISSUE THREAD

**Issue by msbt** [owncloud/tasks#88]
So when I'm working on a (sub)task, I could have a time-tracking option and see how long it took me or others that are part of the project to finish their tasks of it.

You can set a start date now, but only for the project in general, not for single tasks.

**Comment by smatthie** [comment]
Somebody on the forum also requested a time tracker app (I can't find the post now), but having it integrated with task would be much better. I would also find it useful and in my experience many freelancers need some kind of time-tracking to be able to invoice their customers later for the time they spent on projects. It's also important for monitoring and finding out where you waste time.

Essentially you need a start/stop button in the task, press start when you start, stop when you have a break, start again etc. so in the end you have a list at what times you have worked on this task. 

It is definitely separate from the task start/end times because you work on a task several distinct times. It will probably need a new database table with fields taskId, starttime, stoptime. Each time you press start, a new entry is created with starttime, and stop updates the stoptime. Might also add the field duration (stoptime-starttime) to make later calculations easier.

It also needs some summary/analysis to get data like:
* how much time worked on task X (summing all the entries with taskid=X)
* how much time worked today/this week/this month (summing all entries where starttime is today etc)
* which tasks I you worked on in the last few days, e.g. a table where the columns are different tasks, and the rows are dates.

**Comment by smatthie** [comment]
Project Hamster is such a (standalone) time tracker, it has roughly all the features that such a time tracker would need. The screenshots give you the basic ideas: https://projecthamster.wordpress.com/screenshots/

**Comment by pasnox** [comment]
That's a desktop application and make the data only available at the
desktop location.
Definitively not what we want here.

2015-02-14 20:58 GMT+01:00 smatthie <notifications@github.com>:

**Comment by smatthie** [comment]
@pasnox Yes, I just gave Hamster as an example of the range of functionality that would be good to have in owncloud, for those who don't use time trackers. Absolutely no suggestion to use Hamster directly.
